module.exports = {
	// sidebar: [{type: 'autogenerated', dirName: '.'}],

	sidebar: [
		"intro",
		{
			type: 'category',
			label: '🧊 Maya',
			link: {
				type: 'generated-index',
				title: 'Maya',
				description: '以下のページでは、Autodesk Maya（オートデスク マヤ）について解説しています。',
			},
			items: [
				'maya/what_is_maya',

				'maya/for_unreal_engine',
				{
					type: 'category',
					label: 'テクニカルドキュメント',
					link: {
						type: 'generated-index',
						title: 'テクニカルドキュメント',
						description: '以下のページでは、テクニカルアーティストが使用する知識ついて解説しています。',
					},
					items: [
						'maya/script/general',
						'maya/script/open_source_components',
						'maya/script/environment_variable',
						'maya/script/devkit',
					],
				},
			],
		},
		{
			type: 'category',
			label: '🖌️ Substance 3D Painter',
			link: {
				type: 'generated-index',
				title: 'Substance 3D Painter',
				description: '以下のページでは、Adobe Substance 3D Painter（アドビ サブスタンス スリーディー ペインター）について解説しています。',
			},
			items: [
				'substance_3d_painter/what_is_substance_3d_painter'
			],
		},
		{
			type: 'category',
			label: '🎮 Unreal Engine',
			link: {
				type: 'generated-index',
				title: 'Unreal Engine',
				description: '以下のページでは、Unreal Engine（アンリアルエンジン）について解説しています。',
			},
			items: [
				'unreal_engine/what_is_unreal_engine'
			],
		},
		{
			type: 'category',
			label: '🎨 Photoshop',
			link: {
				type: 'generated-index',
				title: 'Photoshop',
				description: '以下のページでは、Adobe社製品のPhotoshop（フォトショップ）について解説しています。',
			},
			items: [
				'photoshop/what_is_photoshop',
				{
					type: 'category',
					label: 'フィルター',
					link: {
						type: 'generated-index',
						title: 'フィルター',
						description: '以下のページでは、フィルターについて解説しています。'
					},
					items: [
						'photoshop/filter/what_is_filter',
						'photoshop/filter/bokeh/bokeh',
					],
				},
			],
		},
		{
			type: 'category',
			label: '📡 OBS Studio',
			link: {
				type: 'generated-index',
				title: 'OBS Studio',
				description: '以下のページでは、OBS Studio（オービーエススタジオ）について解説しています。',
			},
			items: [
				'obs_studio/what_is_obs',
				'obs_studio/install/how_to_install',
				'obs_studio/recommended_setting/streaming',
				'obs_studio/recommended_setting/recording',
				'obs_studio/menu/menu',
				{
					type: 'category',
					label: '設定解説',
					link: {
						type: 'generated-index',
						title: '設定解説',
						description: '以下のページでは、OBS Studio（オービーエススタジオ）の設定項目について解説しています。',
					},
					items: [
						'obs_studio/settings/how_to_start',
						'obs_studio/settings/general/general',
					],
				},
				{
					type: 'category',
					label: '不具合対応',
					link: {
						type: 'generated-index',
						title: '不具合対応',
						description: '以下のページでは、不具合時に確認するべき内容について解説しています。',
					},
					items: [
						'obs_studio/trouble_shooting/log_file',
						'obs_studio/trouble_shooting/cant_open_nvenc_codec'
					],
				},
			]
		},
		{
			type: 'category',
			label: '学術',
			link: {
				type: 'generated-index',
				title: '学術',
				description: '以下のページでは、作品制作に応用する学術的内容をまとめています。',
			},
			items: [
				{
					type: 'category',
					label: '数学',
					link: {
						type: 'generated-index',
						title: '数学',
						description: '以下のページでは、数学に関する知識ついて解説しています。',
					},
					items: [
						'academic/math/equation',
					],
				},
			],
		},
		"terms_of_service",
		"sandbox",
	],
};
