module.exports = {
	// sidebar: [{type: 'autogenerated', dirName: '.'}],

	sidebar: [
		"intro",
		{
		type: 'category',
		label: '📡 OBS Studio',
		link: {
			type: 'generated-index',
			title: 'OBS Studio',
			description: '以下のページでは、OBS Studio（オービーエススタジオ）について解説しています。',
		},
		items: [
			'obs_studio/what_is_obs',
			'obs_studio/how_to_install',
		],
		},
		{
			type: 'category',
			label: '🎨 Photoshop',
			link: {
				type: 'generated-index',
				title: 'Photoshop',
				description: '以下のページでは、Adobe社製品のPhotoshop（フォトショップ）について解説しています。',
			},
			items: [
				'photoshop/what_is_photoshop',
			],
		},
		"sandbox",
	],
};
